[package]
name = "mtga_log_parse"
version = "0.1.0"
authors = ["Justin Shrake <justinshrake@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.7.0"
landlord = {path="../../lib"}
